name: renew

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 1 * * *'
  watch:
    types: started
  workflow_dispatch:

concurrency: renew-con

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: renew
    steps:

      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Create directory
        run: |
         mkdir -p ~/code/

      - name: Unzip scripts
        run: |
         unzip -P ${{ secrets.PASSWD }} code.zip -d ~/code/ > /dev/null
         sudo chmod -R 700 ~/code/*
     
      - name: Run renew scripts
        run: |
          sudo cp /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime > /dev/null

          cd ~/code/AutoRenewE5/
          ./Renew.sh &> /dev/null

      - name: Zip scripts
        run: |
          rm -f code.zip
          cd ~/code
          zip -P ${{ secrets.PASSWD }} code.zip -r ./ > /dev/null

      - name: Prepare to commit
        run: |
          cp ~/code/code.zip code.zip
      
      - name: Commit config
        run: |
         git pull
         git config --global user.email "${{ secrets.EMAIL }}"
         git config --global user.name "${{ secrets.EMAIL }}"
         git add .
         git commit -am "Update rclone config"
         git push